version: '3.8'
services:
  client:
    build:
      context: ./client
    image: client_git
    # restart: always
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    # networks:
    #   - postgresql

  api:
    build:
      context: ./api
    image: api_git
    environment:
      - PORT=5000
      # - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    volumes:
      - ./api/src:/app/src
      - ./api/prisma:/app/prisma
    ports:
      - "4000:5000"
  #   # volumes:
  #   #   - ./server:/app
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    # networks:
    #   - postgresql

# networks:
  # postgresql:
